### ISSUE TITLE
Will save sync issues ever be addressed?

### ISSUE THREAD

**Issue by Damongirl** [Tarnadas/net64plus#90] opened 2019-02-25 07:52 UTC
My friend and I enjoy playing this game together, but one of the biggest things that made us stop playing were the disconnects and stars being grabbed while one person wasn't connected to the server, causing us to become desynced because the star count never updates for the player when he reconnects to the server. We have to resort to sharing save files and that can get annoying after awhile, especially if it's done frequently. So I was hoping this would be addressed in the upcoming versions because we really want to get back into playing again and having this fixed would be awesome.

**Comment by Tarnadas** [comment] 2019-02-25 15:14
See #13 
I agree that it needs to be addressed, but it's not that easy to fix.
The problem is that the emulator code only tells Net64 what has been collected last.

**Comment by Damongirl** [comment] 2019-02-26 01:13
Well I hope someone can figure out a solution for it soon.

**Comment by Tarnadas** [comment] 2020-07-06 19:29
Closing. See #13

**Closed by Tarnadas** 2020-07-06 19:29 UTC
